[project]
name = "fau-generative-security-homework3"
version = "0.1.0"
description = "FAU Generative Security Homework 3"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.3",
    "langchain-diffbot>=0.1.0",
    "langchain-experimental>=0.4.2",
    "langchain-google-genai>=4.4.0",
]

[tool.uv]
package = false
